// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/song_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1363855866394874640),
    name: 'SongEntity',
    lastPropertyId: const obx_int.IdUid(11, 8302990038565693250),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3515473954591334000),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8738682647193473431),
        name: 'songId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7773176647544837561),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5727786205039306467),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6397161080328650990),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8838740298305346235),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4945185647809157456),
        name: 'metronome',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4943066762812987102),
        name: 'duration',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3999537917515274487),
        name: 'trackCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6541298322907433254),
        name: 'isDownloaded',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7691542497404068816),
        name: 'sourcesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8302990038565693250),
        name: 'downloadSources',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1363855866394874640),
    lastIndexId: const obx_int.IdUid(1, 7773176647544837561),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SongEntity: obx_int.EntityDefinition<SongEntity>(
      model: _entities[0],
      toOneRelations: (SongEntity object) => [],
      toManyRelations: (SongEntity object) => {},
      getId: (SongEntity object) => object.id,
      setId: (SongEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SongEntity object, fb.Builder fbb) {
        final songIdOffset = fbb.writeString(object.songId);
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        final categoryOffset = fbb.writeString(object.category);
        final sourcesJsonOffset = fbb.writeString(object.sourcesJson);
        final downloadSourcesOffset = fbb.writeString(object.downloadSources);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, songIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, artistOffset);
        fbb.addOffset(4, categoryOffset);
        fbb.addInt64(5, object.metronome);
        fbb.addFloat64(6, object.duration);
        fbb.addInt64(7, object.trackCount);
        fbb.addBool(8, object.isDownloaded);
        fbb.addOffset(9, sourcesJsonOffset);
        fbb.addOffset(10, downloadSourcesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final songIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final metronomeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final durationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final trackCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final sourcesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final downloadSourcesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final isDownloadedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = SongEntity(
          id: idParam,
          songId: songIdParam,
          title: titleParam,
          artist: artistParam,
          category: categoryParam,
          metronome: metronomeParam,
          duration: durationParam,
          trackCount: trackCountParam,
          sourcesJson: sourcesJsonParam,
          downloadSources: downloadSourcesParam,
          isDownloaded: isDownloadedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SongEntity] entity fields to define ObjectBox queries.
class SongEntity_ {
  /// See [SongEntity.id].
  static final id = obx.QueryIntegerProperty<SongEntity>(
    _entities[0].properties[0],
  );

  /// See [SongEntity.songId].
  static final songId = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[1],
  );

  /// See [SongEntity.title].
  static final title = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[2],
  );

  /// See [SongEntity.artist].
  static final artist = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[3],
  );

  /// See [SongEntity.category].
  static final category = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[4],
  );

  /// See [SongEntity.metronome].
  static final metronome = obx.QueryIntegerProperty<SongEntity>(
    _entities[0].properties[5],
  );

  /// See [SongEntity.duration].
  static final duration = obx.QueryDoubleProperty<SongEntity>(
    _entities[0].properties[6],
  );

  /// See [SongEntity.trackCount].
  static final trackCount = obx.QueryIntegerProperty<SongEntity>(
    _entities[0].properties[7],
  );

  /// See [SongEntity.isDownloaded].
  static final isDownloaded = obx.QueryBooleanProperty<SongEntity>(
    _entities[0].properties[8],
  );

  /// See [SongEntity.sourcesJson].
  static final sourcesJson = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[9],
  );

  /// See [SongEntity.downloadSources].
  static final downloadSources = obx.QueryStringProperty<SongEntity>(
    _entities[0].properties[10],
  );
}
